// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlM1p1oTXOT4J3BitRTY0NOIxXah91wII',
    appId: '1:50621609901:web:46f22de733b5b53e85d324',
    messagingSenderId: '50621609901',
    projectId: 'kids-guard-34c0e',
    authDomain: 'kids-guard-34c0e.firebaseapp.com',
    storageBucket: 'kids-guard-34c0e.firebasestorage.app',
    measurementId: 'G-G3VJQ8JGZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT-SteNfjT_LEpX7wgAmb2DK4GcncU_eY',
    appId: '1:50621609901:android:6220e0441f461f2d85d324',
    messagingSenderId: '50621609901',
    projectId: 'kids-guard-34c0e',
    storageBucket: 'kids-guard-34c0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB931hAiHOHQxGPzdbyhZSuD2_fu_d3DKA',
    appId: '1:50621609901:ios:fc0a0b9ff03a642c85d324',
    messagingSenderId: '50621609901',
    projectId: 'kids-guard-34c0e',
    storageBucket: 'kids-guard-34c0e.firebasestorage.app',
    iosBundleId: 'com.example.kidsGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB931hAiHOHQxGPzdbyhZSuD2_fu_d3DKA',
    appId: '1:50621609901:ios:fc0a0b9ff03a642c85d324',
    messagingSenderId: '50621609901',
    projectId: 'kids-guard-34c0e',
    storageBucket: 'kids-guard-34c0e.firebasestorage.app',
    iosBundleId: 'com.example.kidsGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlM1p1oTXOT4J3BitRTY0NOIxXah91wII',
    appId: '1:50621609901:web:a6669a2534b916a185d324',
    messagingSenderId: '50621609901',
    projectId: 'kids-guard-34c0e',
    authDomain: 'kids-guard-34c0e.firebaseapp.com',
    storageBucket: 'kids-guard-34c0e.firebasestorage.app',
    measurementId: 'G-93V6YPQM4C',
  );
}
